[build]
  command = "npm run build"
  publish = ".next"

[dev]
  command = "npm run dev"
  port = 9002

# Uncomment below if you want to set environment variables
#[[redirects]]
#  from = "/api/*"
#  to = "/.netlify/functions/:splat"
#  status = 200
